"""Shared language lists used by settings and panel dropdowns."""

TOP_50_LANGUAGES = [
    "Mandarin Chinese",
    "Spanish",
    "English",
    "Hindi",
    "Bengali",
    "Portuguese",
    "Russian",
    "Japanese",
    "Punjabi",
    "Marathi",
    "Telugu",
    "Wu Chinese",
    "Turkish",
    "Korean",
    "French",
    "German",
    "Vietnamese",
    "Tamil",
    "Yue Chinese (Cantonese)",
    "Urdu",
    "Javanese",
    "Italian",
    "Egyptian Arabic",
    "Gujarati",
    "Iranian Persian",
    "Bhojpuri",
    "Southern Min",
    "Hakka Chinese",
    "Jin Chinese",
    "Hausa",
    "Kannada",
    "Indonesian",
    "Polish",
    "Yoruba",
    "Xiang Chinese",
    "Malayalam",
    "Odia",
    "Maithili",
    "Ukrainian",
    "Sunda",
    "Arabic (Modern Standard)",
    "Uzbek",
    "Sindhi",
    "Amharic",
    "Fula",
    "Romanian",
    "Oromo",
    "Igbo",
    "Tagalog",
    "Serbian",
    # European national/state languages not covered by the original top-language list.
    "Albanian",
    "Armenian",
    "Azerbaijani",
    "Belarusian",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "Estonian",
    "Finnish",
    "Georgian",
    "Greek",
    "Hungarian",
    "Icelandic",
    "Irish",
    "Latvian",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Maltese",
    "Montenegrin",
    "Norwegian",
    "Romansh",
    "Slovak",
    "Slovene",
    "Swedish",
    # Historical and reconstructed Indo-European languages with written traditions
    # where applicable. Proto-Indo-European is reconstructed, not attested in writing.
    "Proto-Indo-European (reconstructed)",
    "Anatolian: Hittite",
    "Anatolian: Luwian",
    "Anatolian: Lycian",
    "Avestan",
    "Classical Armenian",
    "Classical Sanskrit",
    "Vedic Sanskrit",
    "Pali",
    "Old Persian",
    "Ancient Greek",
    "Mycenaean Greek",
    "Latin",
    "Old Italic: Oscan",
    "Old Italic: Umbrian",
    "Gothic",
    "Old Norse",
    "Old English",
    "Old High German",
    "Old Saxon",
    "Old Irish",
    "Gaulish",
    "Celtiberian",
    "Old Church Slavonic",
    "Old East Slavic",
    "Tocharian A",
    "Tocharian B",
    "Phrygian",
    "Messapic",
    # Historical East Asian languages and classical written forms.
    "Old Japanese",
    "Classical Japanese",
    "Kanbun",
    "Old Chinese",
    "Middle Chinese",
    "Classical Chinese",
    "Literary Chinese",
    "Old Korean",
    "Middle Korean",
    "Old Tibetan",
    "Classical Tibetan",
    "Tangut",
    "Khitan",
    "Jurchen",
    "Classical Mongolian",
    "Old Vietnamese",
]

# Preserve the app's existing language defaults on first run/migration.
DEFAULT_ENABLED_LANGUAGES = ["English", "Serbian", "Italian", "French", "Japanese"]
