"""Shared language lists used by settings and panel dropdowns."""

TOP_50_LANGUAGES = [
    "Mandarin Chinese",
    "Spanish",
    "English",
    "Hindi",
    "Bengali",
    "Portuguese",
    "Russian",
    "Japanese",
    "Punjabi",
    "Marathi",
    "Telugu",
    "Wu Chinese",
    "Turkish",
    "Korean",
    "French",
    "German",
    "Vietnamese",
    "Tamil",
    "Yue Chinese (Cantonese)",
    "Urdu",
    "Javanese",
    "Italian",
    "Egyptian Arabic",
    "Gujarati",
    "Iranian Persian",
    "Bhojpuri",
    "Southern Min",
    "Hakka Chinese",
    "Jin Chinese",
    "Hausa",
    "Kannada",
    "Indonesian",
    "Polish",
    "Yoruba",
    "Xiang Chinese",
    "Malayalam",
    "Odia",
    "Maithili",
    "Ukrainian",
    "Sunda",
    "Arabic (Modern Standard)",
    "Uzbek",
    "Sindhi",
    "Amharic",
    "Fula",
    "Romanian",
    "Oromo",
    "Igbo",
    "Tagalog",
    "Serbian",
]

# Preserve the app's existing language defaults on first run/migration.
DEFAULT_ENABLED_LANGUAGES = ["English", "Serbian", "Italian", "French", "Japanese"]
